### ISSUE TITLE
When overwrites, forget to delete the corresponding element in `activeResourcePriorities`

### ISSUE THREAD

**Issue by Ayuilos** [rmrk-team/evm#106]
https://github.com/rmrk-team/evm/blob/dev/contracts/RMRK/multiresource/AbstractMultiResource.sol#L183

**Comment by Ayuilos** [comment]
If that's a overwrite, I think it's better to just do the overwrite action than delete and push.

**Comment by steven2308** [comment]
This was fixed on https://github.com/rmrk-team/evm/pull/117
