### ISSUE TITLE
maxSupply: possibility to mint unlimited number of NFTs

### ISSUE THREAD

**Issue by ilionic** [rmrk-team/evm#145]
In rmrk-pallets and original kusama spec `maxSupply` 0 equals to infinite number of tokens allowed to mint.

**Comment by ThunderDeliverer** [comment]
This would require additional logic to be implemented. As it is now, you can pass `256^2-1` as a `maxSupply` to the smart contract and get the maximum, virtually infinite, value.

I don't think it's worth it to implement in EVM as we are struggling with contract sizes as it is already. 🤔

**Comment by ilionic** [comment]
Ok, makes sense. In this case we’ll just keep 0 as infinite implementation in pallets and ink.
