### ISSUE TITLE
Should `SetEquippableToAll(uint64 indexed partId)` be emitted when `_addEquippableAddresses` etc?

### ISSUE THREAD

**Issue by Ayuilos** [rmrk-team/evm#154]
https://github.com/rmrk-team/evm/blob/master/contracts/RMRK/catalog/RMRKCatalog.sol

I found that when `_addEquippableAddresses`, `_setEquippableAddresses` or `_resetEquippableAddresses`,
```solidity
delete _isEquippableToAll[partId]
```
is excuted, but no `SetEquippableToAll(uint64 indexed partId)` emit.

If your indexer just listen to `SetEquippableToAll(...)` event to update the `equippableToAll` state of part, you won't get the real time data.

**Comment by Ayuilos** [comment]
No problem, I used to think this event will include if equippableToAll is `true` or `false`. Now I know this event just indicates that the status is set to `true`

**Comment by steven2308** [comment]
I agree it's a good alternative, but we can also live without it. The detail with the current implementation is that the indexer must beware that both `AddedEquippables` and `SetEquippables` override the _equippable to all_ status.

**Comment by Ayuilos** [comment]
True, that's also acceptable, just need to do more state update actions in several functions.
