### ISSUE TITLE
`RMRKCatalog` has no way to set `metadataURI`

### ISSUE THREAD

**Issue by Ayuilos** [rmrk-team/evm#157]
There's no `_setMetadataURI` function and the `_metadataURI` is `private`, so there's no way for me to inherit this contract and set `_metadataURI`.
I think you `internal` `_metadataURI` or give a `_setMetadataURI`, maybe better `internal`ing `_metadataURI` which will be more flexible for 2nd develop.

https://github.com/rmrk-team/evm/blob/master/contracts/RMRK/catalog/RMRKCatalog.sol

**Comment by steven2308** [comment]
Good point. I'll add `_setMetadataURI` to be consistent with other implementations. Will do the same with `_setType`.

**Comment by steven2308** [comment]
Addressed in this PR: https://github.com/rmrk-team/evm/pull/158
