### ISSUE TITLE
Add transferable flag

### ISSUE THREAD

**Issue by Swader** [rmrk-team/evm#21]
Simple “transferable” flag to be set on the collection, bool, set on mint and not mutable later. Needed for gems and all the “soulbound” stuff.

In Kusama’s implementation we also have a modifier for temporary transferability, so that you can say, this becomes non transferable after X blocks, or it is transferable for only X blocks, but to not complicate things just the basic boolean would do.

Concept is explained [here](https://docs.rmrk.app/nontransferable).

**Comment by steven2308** [comment]
This is possible now with the [soulbound extension](https://github.com/rmrk-team/evm/blob/dev/contracts/RMRK/extension/soulbound/RMRKSoulbound.sol)
