### ISSUE TITLE
Cannot install `rmrk-team/evm-contract`

### ISSUE THREAD

**Issue by 1337-ishaan** [rmrk-team/evm#219]
![image](https://github.com/rmrk-team/evm/assets/64636222/e8c0fdb4-174f-4856-afbb-9d097f645ba6)

Pls check the above image, tried installing with `yarn` & `npm`, but throwing Error for both the case.

Do we have any workaround with this?

**Comment by steven2308** [comment]
Hey there, I think you're simply missing an "s" at the end:
https://www.npmjs.com/package/@rmrk-team/evm-contracts

**Comment by 1337-ishaan** [comment]
Correct, fixed it in the documentation in #220
