### ISSUE TITLE
Some questions about `MultiResource_EIP` in `eip` branch

### ISSUE THREAD

**Issue by Ayuilos** [rmrk-team/evm#22]
I have questions about why these two functions did not get modified by `virtual`?

https://github.com/rmrk-team/evm/blob/eip/contracts/MultiResource_EIP/MultiResourceToken.sol#L389
https://github.com/rmrk-team/evm/blob/eip/contracts/MultiResource_EIP/MultiResourceToken.sol#L410

If so, this would mean that every resource in a project that directly publishes the standard as NFT can be accepted or rejected by anyone at will.

**Comment by steven2308** [comment]
This is for an EIP, EIPs care about the interface only. Implementations can add guards at will. For instance one would expect only the owner of the token to accept resources. (Check for instance OpenZeppelin's [implementation of ERC721](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L114)) 
This is just a sample implementation, we want to keep it simple. Also, this is a work in progress.

If you're asking specifically about the `override`, it does look missing. Will check.

Thanks for your interest!

**Comment by Ayuilos** [comment]
> This is for an EIP, EIPs care about the interface only. Implementations can add guards at will. For instance one would expect only the owner of the token to accept resources. (Check for instance OpenZeppelin's [implementation of ERC721](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L114)) This is just a sample implementation, we want to keep it simple. Also, this is a work in progress.
> 
> If you're asking specifically about the `override`, it does look missing. Will check.
> 
> Thanks for your interest!

I mean, since your code is listed there, why not do everything right? If you had taken care of this in the first place, I wouldn't be asking questions here, would I?
---
Suppose you submit the current code as an EIP.
If I were an reviewer, and I saw that there was an detailed code instead of just an interface, I would assume that that exists as implementation code. But the implementation code I mentioned above doesn't seem to work out of the box. I can't even inherit this contract because those 2 functions can't be `override`.
