### ISSUE TITLE
Catalog implementation with a mapping and method to get all partIds

### ISSUE THREAD

**Issue by Yuripetusko** [rmrk-team/evm#259]
Currently without the indexer or without quering all PartsAdded events, there's no way to get all partIds. It doesn't help also that partIds are not sequential. 

It would be great to have an implementation of Catalog (and list it as recommended) which as a view function to get all part ids.

**Comment by steven2308** [comment]
We can add an extension to it, similar to ERC72Enumerable. Where you get a view to get parts by index or by batches. Getting all parts is dangerous since eventually it could break the gas limit (even if a view).  
Then we make this catalog the default implementation.

**Comment by Yuripetusko** [comment]
This is now solved https://github.com/rmrk-team/evm/pull/261
