### ISSUE TITLE
Duplicate check is needed in `addChild`

### ISSUE THREAD

**Issue by Ayuilos** [rmrk-team/evm#51]
I think here lost duplicate check:
https://github.com/rmrk-team/evm/blob/d921674ddd3b9b751f549f6efb8d08d1eb86d409/contracts/RMRK/RMRKNesting.sol#L396

The same child could be added unlimited times.

**Comment by Ayuilos** [comment]
So I think maybe the `hasChild` function is still needed.
But I agree add child position mapping solution more, because doing hard search costs so much.

**Comment by steven2308** [comment]
You're correct. You could add the same child multiple times. But you'd only be wasting gas yourself.
If we want to prevent this with a check, we will increase the gas cost for every regular use, which is just adding a child once. We try to optimize for common cases, so I don't think it's worth it.
If a user considers this important, they can simply extend this contract and this check.
