### ISSUE TITLE
Remove the redundant _ from the variable

### ISSUE THREAD

**Issue by ThunderDeliverer** [rmrk-team/evm#68]
https://github.com/rmrk-team/evm/blob/31b092cd32a68e32ca79f361199d500aeca5db98/contracts/implementations/RMRKBaseStorageImpl.sol#L19

The `type_` variable has two `_` characters. This seems redundant and could be removed.

So in short:

`type__` => `type_`

**Comment by steven2308** [comment]
The problem in this case is that there methods named symbol and type_ for the getters, so we get a warning of shadowing an existing declaration.

**Comment by ThunderDeliverer** [comment]
What if we renamed it then? Maybe to `baseType_`? This shouldn't impact any contracts importing it, so it would just make the variable easier to read.

**Comment by steven2308** [comment]
The getter was renamed in the end and we made sure only mandatory trailing scores were left.
