### ISSUE TITLE
Should revert when try to transfer NFT to itself

### ISSUE THREAD

**Issue by Ayuilos** [rmrk-team/evm#69]
If try to transfer NFT to itself, should revert it.
Rightnow the code will cause an infinite loop when run `ownerOf` in `_approve` in `_updateOwnerAndClearApprovals`.

**Comment by steven2308** [comment]
Great catch! Will fix soon.
Thanks @Ayuilos !

**Comment by steven2308** [comment]
Fixed on [this commit](https://github.com/rmrk-team/evm/commit/dfc0d07f137670adf332ea7c271a853213f04d4c)
