### ISSUE TITLE
Add Resource-replace param

### ISSUE THREAD

**Issue by Swader** [rmrk-team/evm#7]
When adding a new resource, an issuer should be able to specify the ID of an existing one which would get overwritten. This is necessary to be able to upgrade NFTs, change their parts, or even just do reveal mechanics of certain types.

This should be an extra parameter passed alongside the add resource call.

**Comment by CicadaNCR** [comment]
This is already implemented as the parameter `_overwrites` passed to `addResourceToToken()` in RMRKCore.sol. Tests pending!
