### ISSUE TITLE
After `_unnestChild`, position of exchanged child(last child) in `_posInChildArray` is not updated

### ISSUE THREAD

**Issue by Ayuilos** [rmrk-team/evm#79]
As I mentioned in title,
We have `[A, B, C]` in `_children[1]`, after `unnestChild(1, 0, address(0))`, `_children[1]` will become `[C, B]`, but `_posInChildArray[CAddr][CId]` was still 2.

**Comment by Ayuilos** [comment]
Seems not just only this function, any function has called `_removeChildByIndex` should be cared.

**Comment by steven2308** [comment]
You're right! We must fix this on burnChild and unnest. 
I'll try to find a not very expensive solution. Thanks!

**Comment by steven2308** [comment]
I changed the strategy to use a flag instead of a position. Now it's updated in burn and unnest.
[PR here](https://github.com/rmrk-team/evm/pull/83)
