### ISSUE TITLE
Should `reclaimChild` need to check the child is not in `_pendingChildren` and `_children`?

### ISSUE THREAD

**Issue by Ayuilos** [rmrk-team/evm#80]
Because when child is in `pendingChildren` or `children`, the `reclaimChild` can still be called and this will cause record issue.

**Comment by steven2308** [comment]
That makes sense, right know it will probably produce an inconsistency. Will fix soon.

**Comment by steven2308** [comment]
Added protection on [this PR](https://github.com/rmrk-team/evm/pull/83)
Thanks!
