### ISSUE TITLE
Will that be more direct and intuitive if set the uninitialized priority to `2^16 - 1` in `_acceptChild`?

### ISSUE THREAD

**Issue by Ayuilos** [rmrk-team/evm#84]
`2^16 - 1 = 65535`
The client can easily handle this number and everywhere still make sense. For client there's no need to resolve the special `0` anymore.

**Comment by steven2308** [comment]
We went a little different on https://github.com/rmrk-team/evm/pull/117
The new priority is set to the previous length of the array. So first child has a priority of 0, second: 1, third: 2 and so on. This way the older children have higher priority and there's no duplication.
