### ISSUE TITLE
Moar Tests

### ISSUE THREAD

**Issue by ed-iv** [rmrk-team/evm#9]
The following is a list of methods in the public API that looked like they could use test coverage:

- General
    - [ ] `approve`
    - [ ] `isApprovedOrOwner`
    - [ ] `getApproved`
    - [ ] `tokenURI`
- Resources
    - [ ] `getResourceObject`
    - [ ] `getResourceOverwrites`
    - [ ] `hashResource16`
- Introspection
    - [ ] `isRmrkCore`
- Nesting
    - [ ] `deleteChildFromChildren`
    - [ ] `setChild`
- Transfers
    - [ ] `transfer`
    - [ ] `transferFrom`
- Royalties
    - [ ] `getRoyaltyData`
    - [ ] `setRoyaltyData`

**Comment by steven2308** [comment]
Besides royalties which are not yet implemented, everything else is covered or removed.
